fixed comments and v-show
js-tasks-ru/vue-20201210_grebady pull request #4
Opened 2021-03-17 08:16 UTC by Grebady

2021-03-17 08:16 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-18 08:25 UTC, ShGKme requested changes
Требуется добавить вычисляемое свойство в DropdownButton все вычислений внутри шаблона.

2021-03-18 08:25 UTC, ShGKme commented on 03-vue-cli/03-AppToast/components/AppToast.vue
> +      </div>
Осталось дублирование кода...

2021-03-18 08:25 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/assets/styles/_button.css
> +.button {
Требовалось ли создавать этот файл?

2021-03-18 08:25 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/assets/styles/_dropdown.css
> +.dropdown {
Требовалось ли создавать этот файл?

2021-03-18 08:25 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +        :class="{dropdown__item_icon: options.some(element => !!element.icon)}"
Лучше избегать добавления такой логики в шаблон. Для вычисления класса у каждой кнопки запускается поиск по всему массиву вариантов, и так будет при каждом ререндеринге.

Здесь однозначно требуется вычисляемое свойство.

2021-03-23 13:33 UTC, ShGKme requested changes
Требуется добавить стили

2021-03-23 13:33 UTC, ShGKme commented on 04-SPA/04-Layouts/components/AuthLayout.vue
Не хватает стилей:
https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/styles/_page_onboarding.css

2021-03-23 13:33 UTC, ShGKme commented on 04-SPA/04-Layouts/components/FormLayout.vue
Не хватает стилей: https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/styles/_page_forms.css

2021-03-23 13:33 UTC, ShGKme commented on 04-SPA/04-Layouts/components/TheHeader.vue
> +          <img src="/assets/logo.svg" alt="Meetups"/></a>
Здесь также лучше использовать `<router-link>`

2021-03-23 13:33 UTC, ShGKme commented on 04-SPA/04-Layouts/views/FormPage.vue
> +  <form-layout :title="'Создать митап'">
Если значение параметра - просто строка, его можно передать без директивы привязки к JS выражению `title="Создать митап"`

2021-03-23 13:33 UTC, ShGKme commented on 04-SPA/04-Layouts/components/BaseLayout.vue
> +      <router-view />
Предлагается `BaseLayout` реализовывать также, как остальные компоненты-лейауты. Т.е. как компонент, который имеет общее для множества страниц, а содержимое получает через слот. `<router-view />` уже передаётся в него в `App.vue`

2021-03-23 13:43 UTC, ShGKme commented on 04-SPA/06-Query/router/index.js
> +  duplicateNavigationPolicy: 'ignore',
Кажется, такой опции нет во vue-router. Она только обсуждалась

2021-03-23 13:46 UTC, ShGKme commented on 04-SPA/06-Query/router/index.js
> +  duplicateNavigationPolicy: 'ignore',
При запуске тестирования `npm test` остаётся ошибка с NavigationDuplicated

2021-03-23 16:39 UTC, ShGKme approved these changes
Все задачи приняты 🎉

2021-03-23 16:42 UTC, merged